"""add blog comment table

Revision ID: 0da2a49c48d4
Revises: e42f3d983e65
Create Date: 2026-07-09 11:49:19.136225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da2a49c48d4'
down_revision = 'e42f3d983e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], name=op.f('fk_blog_comments_blog_id_blogs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_blog_comments_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_comments')
    # ### end Alembic commands ###
