"""create events database

Revision ID: 8236bda3779c
Revises: f38b9b02ef4d
Create Date: 2026-07-13 15:52:19.287573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8236bda3779c'
down_revision = 'f38b9b02ef4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_events_site_id_sites')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_site_images_site_id_sites')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('site_img_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_img_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('site_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name='fk_site_img_model_site_id_sites'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('site_images')
    op.drop_table('events')
    # ### end Alembic commands ###
