"""create inhabitants db

Revision ID: 83348b75b0eb
Revises: 0da2a49c48d4
Create Date: 2026-07-13 10:52:58.051239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83348b75b0eb'
down_revision = '0da2a49c48d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inhabitants_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('banner_img', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inhabitants_model')
    # ### end Alembic commands ###
