"""create project model

Revision ID: d942fa46288f
Revises: d9d28ca85bda
Create Date: 2026-07-16 15:45:04.941856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd942fa46288f'
down_revision = 'd9d28ca85bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('p1_img', sa.String(), nullable=True),
    sa.Column('p2_img', sa.String(), nullable=True),
    sa.Column('p3_img', sa.String(), nullable=True),
    sa.Column('video', sa.String(), nullable=True),
    sa.Column('intro_info', sa.String(), nullable=False),
    sa.Column('main_info', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
