"""set up a one to many relationship between inhabitants and sites

Revision ID: e161884a6fbe
Revises: 83348b75b0eb
Create Date: 2026-07-13 10:58:32.694462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e161884a6fbe'
down_revision = '83348b75b0eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inhabitants_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_inhabitants_model_site_id_sites'), 'sites', ['site_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inhabitants_model', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_inhabitants_model_site_id_sites'), type_='foreignkey')
        batch_op.drop_column('site_id')

    # ### end Alembic commands ###
